name: Pre Merge Queue Tasks

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  # This job needs to be called main (the same as the ci.yml workflow)
  # because of how merge queues work: https://stackoverflow.com/a/78030618
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
