name: Post Release Tasks

on:
  release:
    types: [published]

jobs:
  publish-python:
    name: ""
    uses: ./.github/workflows/publish-python.yml
    secrets: inherit
  publish-crates:
    name: ""
    uses: ./.github/workflows/publish-crates.yml
    secrets: inherit
  adjust-versions:
    runs-on: [self-hosted, skylake40]
    container:
      image: ghcr.io/feldera/feldera-dev:7217ddac83a36a020b733cd7f650825349d351e3
      options: --user=ubuntu
    needs: [publish-crates, publish-python]
    steps:
      - uses: actions/checkout@v4
      - name: Determine current version based on pipeline-manager
        run: |
          echo "CURRENT_VERSION=$(cargo metadata --no-deps | jq -r '.packages[]|select(.name == "pipeline-manager")|.version')" >> $GITHUB_OUTPUT
      # The docker container when executed in the action runs with a different home directory
      # than we set in the dev container (?), hence this step is necessary (sigh)
      # https://github.com/actions/runner/issues/863
      - name: Rustup set default toolchain
        run: rustup default stable
      - name: Bump cargo versions
        run: |
          cargo set-version --bump ${{ vars.RELEASE_NEXT_VERSION }} -p feldera-types
          cargo set-version --bump ${{ vars.RELEASE_NEXT_VERSION }} -p feldera-storage
          cargo set-version --bump ${{ vars.RELEASE_NEXT_VERSION }} -p dbsp
          cargo set-version --bump ${{ vars.RELEASE_NEXT_VERSION }} -p fda
          cargo set-version --bump ${{ vars.RELEASE_NEXT_VERSION }} -p pipeline-manager
          cargo set-version --bump ${{ vars.RELEASE_NEXT_VERSION }} -p feldera-sqllib
      - name: Determine next version based on pipeline-manager
        run: |
          echo "NEXT_VERSION=$(cargo metadata --no-deps | jq -r '.packages[]|select(.name == "pipeline-manager")|.version')" >> $GITHUB_OUTPUT
      - name: Adjust python versions
        working-directory: ./python
        run: |
          sed -i.backup "s/version = \"${CURRENT_VERSION}\"/version = \"${NEXT_VERSION}\"/g" pyproject.toml
          uv sync
      - name: List changes
        run: |
          git diff
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: "ci: Bump versions to $NEXT_VERSION"
