name: Create a new release

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "SHA to release"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA_TO_RELEASE: ${{ github.event.inputs.sha || github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ env.SHA_TO_RELEASE }}

      - name: Determine version to release based on pipeline-manager
        run: |
          echo "CURRENT_VERSION=$(cargo metadata --no-deps | jq -r '.packages[]|select(.name == "pipeline-manager")|.version')" >> $GITHUB_ENV

      - name: Check if version is already released (do we have git tag for this version?)
        run: |
          if git tag -l | grep -q "^v${CURRENT_VERSION}$"; then
            echo "Version ${CURRENT_VERSION} is already released"
            exit 1
          fi

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: ci.yml
          workflow_conclusion: success
          commit: ${{ env.SHA_TO_RELEASE }}
          name: feldera-sql-compiler-*|feldera-binaries-*
          name_is_regexp: true
          skip_unpack: true
          if_no_artifact_found: fail

      - name: Attach version to binaries
        run: |
          mv feldera-binaries-aarch64-unknown-linux-gnu.zip feldera-binaries-v${{ env.CURRENT_VERSION }}-aarch64-unknown-linux-gnu.zip
          mv feldera-binaries-x86_64-unknown-linux-gnu.zip feldera-binaries-v${{ env.CURRENT_VERSION }}-x86_64-unknown-linux-gnu.zip
          mv feldera-sql-compiler.zip feldera-sql-compiler-v${{ env.CURRENT_VERSION }}.zip

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          generate_release_notes: true
          make_latest: true
          files: |
            feldera-binaries-v${{ env.CURRENT_VERSION }}-aarch64-unknown-linux-gnu.zip
            feldera-binaries-v${{ env.CURRENT_VERSION }}-x86_64-unknown-linux-gnu.zip
            feldera-sql-compiler-v${{ env.CURRENT_VERSION }}.zip
