name: Upload crates.io packages

on:
  workflow_call:
  workflow_dispatch:

env:
  CARGO_PUBLISH_FLAGS: "--dry-run"

jobs:
  deploy:
    runs-on: [self-hosted, skylake40]
    container:
      image: ghcr.io/feldera/feldera-dev:3012ef118aaaa2b7d49e1dfeda938288a70ba66c
      options: --user=ubuntu
      volumes:
        - /sccache:/sccache
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo publish
        run: |
          cargo publish  ${{ env.CARGO_PUBLISH_FLAGS }} --package feldera-types
          cargo publish  ${{ env.CARGO_PUBLISH_FLAGS }} --package feldera-storage
          cargo publish  ${{ env.CARGO_PUBLISH_FLAGS }} --package dbsp
          cargo publish  ${{ env.CARGO_PUBLISH_FLAGS }} --package fda
          cargo publish  ${{ env.CARGO_PUBLISH_FLAGS }} --package feldera-sqllib
